name: CI — Python tests

on:
  push:
    branches: ["main", "master", "**"]
  pull_request:
    branches: ["main", "master"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install -r backend/requirements-dev.txt

      - name: Run linters (ruff)
        run: |
          ruff check .

      - name: Format check (black)
        run: |
          black --check .

      - name: Run type checks (mypy)
        run: |
          mypy . --ignore-missing-imports

      - name: Run tests
        run: |
          pytest -q --maxfail=1 --disable-warnings

      - name: Upload pytest results (Junit)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-failures
          path: ./
